# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wahid Emalution
email: admin@wahidemalution.com
description: >
  Berbagi semua yang saya tahu, kalau saya tidak tau tidak saya bagikan. Mulai dari pengalaman, Linux, Wordpress, Panel, Coding, random stuff, dsb.
logo: "/assets/images/miku.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wahidemalution.com" # the base hostname & protocol for your site
paginate:	4 # The number of posts to show per page on your homepage

name: 'Wahid Husain'
bio: >
  Hi! Saya wahid husain, kalau kamu kenal sama saya pasti kenal sama saya.
  Begitupun sebaliknya, kalau nda kenal kamu pasti nda kenal sama saja.
author_image: "/assets/images/author.png"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
